name: place_repository
description: Repository of place
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^4.4.0
  google_places_flutter: ^2.0.8
  http: ^1.2.1
  path_provider: ^2.1.3
  path: ^1.9.0
  intl: ^0.19.0
  sealed_languages: ^1.5.0
  

  # trip_repository: 
  #   path: ../trip_repository
  # group_repository: 
  #   path: ../group_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true